requires 'Plack',  0.9980;
requires 'Starman',  0.2000;
 requires 'Test::More';
requires 'YAML';
requires 'Dancer2';
requires 'Plack::Request';
requires 'Config::General';
requires 'Modern::Perl';
requires 'autodie';
requires 'Carp';
requires 'Dancer2::Plugin::Ajax';
requires 'Dancer2::Test';
requires 'Data::Dump';
requires 'DateTime';
requires 'Exporter::NoWork';
requires 'ExtUtils::MakeMaker';
requires 'File::Find';
requires 'File::Spec::Functions';
requires 'File::Temp';
# requires 'Google::Travel::Matrix';
requires 'HTML::Lint';
requires 'List::MoreUtils';
requires 'List::Util';
requires 'Log::Any::Adapter';
requires 'Log::Log4perl';
# requires 'Mover::Form::Travel::Matrix';
requires 'Regexp::Common';
requires 'Template';
requires 'Test::Exception';
requires 'Test::WWW::Mechanize';
requires 'Try::Tiny';
requires 'utf8::all';
# requires 'HTML::FormHandler::Moose'; 
requires 'MooseX::UndefTolerant::Attribute'; 
requires 'Readonly'; 
requires 'DBI'; 
requires 'DBD::SQLite'; 
